introduce common folder

diff --git a/templates/default/ssc-fetch-secrets.sh.erb b/templates/default/ssc-fetch-secrets.sh.erb
--- a/templates/default/ssc-fetch-secrets.sh.erb
+++ b/templates/default/ssc-fetch-secrets.sh.erb
@@ -39,6 +39,7 @@ for U in $SECRET_SERVICE_IGNORE_USERS;do
   EXCLUDE="$EXCLUDE --exclude $U/"
 done
 
+echo "get users..."
 echo "rsync -avxz --delete --exclude password $EXCLUDE -e "ssh -i ${SECRET_SERVICE_ACCESSUSERKEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
 ${SECRET_SERVICE_ACCESSUSER}@${SECRET_SERVICE_SERVER_HOST}:${SECRET_SERVICE_SERVER_REPO}/${SECRET_SERVICE_DOMAIN}/user/ \
 ${SECRET_SERVICE_CLIENT_REPO}/user/"
@@ -46,6 +47,20 @@ ${SECRET_SERVICE_CLIENT_REPO}/user/"
 rsync -avxz --delete --exclude password $EXCLUDE -e "ssh -i ${SECRET_SERVICE_ACCESSUSERKEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
 ${SECRET_SERVICE_ACCESSUSER}@${SECRET_SERVICE_SERVER_HOST}:${SECRET_SERVICE_SERVER_REPO}/${SECRET_SERVICE_DOMAIN}/user/ \
 ${SECRET_SERVICE_CLIENT_REPO}/user/
+
+if [ $? -ne 0 ];then
+  echo 'ERROR: Failed to fetch secrets from secret-server!'
+  exit 1
+fi
+
+echo "get common files..."
+echo "rsync -avxz -e "ssh -i ${SECRET_SERVICE_ACCESSUSERKEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
+${SECRET_SERVICE_ACCESSUSER}@${SECRET_SERVICE_SERVER_HOST}:${SECRET_SERVICE_SERVER_REPO}/${SECRET_SERVICE_DOMAIN}/common/ \
+${SECRET_SERVICE_CLIENT_REPO}/common/"
+
+rsync -avxz -e "ssh -i ${SECRET_SERVICE_ACCESSUSERKEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
+${SECRET_SERVICE_ACCESSUSER}@${SECRET_SERVICE_SERVER_HOST}:${SECRET_SERVICE_SERVER_REPO}/${SECRET_SERVICE_DOMAIN}/common/ \
+${SECRET_SERVICE_CLIENT_REPO}/common/
 
 if [ $? -ne 0 ];then
   echo 'ERROR: Failed to fetch secrets from secret-server!'
